fix: fixed incorrect example text in combobox component
shadcn-ui/ui pull request #1284
Opened 2023-08-19 09:18 UTC by rajgop1

Dear @shadcn 
I hope this message finds you well. I would like to report a potential bug that I've encountered in the ComboBox component.

Bug Description:
In the example provided within the ComboBox component, there seems to be a text error. The displayed text reads "Select Framework," but I believe it should actually say "Select Language." This inconsistency appears to be a result of a copy-paste error during the creation of the example.

2023-08-19 09:39 UTC, dan5py requested changes
@rajgop1 Can you also update the `default` style one? Thanks.

2023-08-19 11:31 UTC, rajgop1 commented
@dan5py Thank you for pointing that out, I have updated default style too.

2023-08-19 11:49 UTC, dan5py approved these changes
👍

2025-03-27 23:44 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2026-08-31 23:44 UTC, closed without merging