fix(www): Backspace Bug in Command component's Demo
shadcn-ui/ui pull request #1286
Opened 2023-08-19 12:43 UTC by divyammadhok

Fixes #1052 

Support for value has been added to each individual command item so that the issue faced in the linked issue is not faced by the users for a better docs experience.

CMDK team suggests that we add a unique value prop to the item for reliable searching https://github.com/pacocoursey/cmdk#faq

2023-08-31 13:54 UTC, divyammadhok commented
@shadcn This PR is ready for review

2023-08-31 15:00 UTC, shadcn commented
@divyammadhok Is this still reproducible on the site? I merged a similar fix for this in https://github.com/shadcn-ui/ui/pull/455

2023-08-31 16:16 UTC, divyammadhok commented
@shadcn I can still reproduce the bug in the docs. Also the deployed instance in #455 i.e. https://ui-git-fork-sammyhass-fix-docs-command-menu-shadcn-pro.vercel.app/docs/components/command does not work as expected too.

2023-09-01 17:26 UTC, divyammadhok commented
@shadcn I believe that the doc for Commanf is now working as expected on this PR's hosted vercel as well.

2023-09-11 20:33 UTC, divyammadhok commented
Hey @shadcn Did you get a chance to look into this PR?

2023-10-20 00:37 UTC, Gravy59 commented
This issue is reproducible on the [main site](https://ui.shadcn.com/docs/components/command).

Type cal -> "Calculator" and "Calendar" show up
type cale -> only "Calendar" shows up

backspace -> only "Calendar" shows up

Looking at the [preview build](https://ui-git-fork-divyammadhok-fix-command-demo-shadcn-pro.vercel.app/docs/components/command), this is resolved.

2023-10-21 22:12 UTC, miquelvir commented
The issue is still reproducible on main, but it impacts more places than just this one. #1522 has a fix for all of them.

2023-10-21 22:13 UTC, miquelvir requested changes
You are missing new york theme and many more places where this issue happens. See #1522 and consider closing this

2025-03-27 23:44 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-06-16 23:55 UTC, brandonmcconnell commented
This was already fixed together with others in #1522

Please close as duplicate of #1450

2026-08-31 23:44 UTC, closed without merging