fix: context menu example in mobile device
shadcn-ui/ui pull request #166
Opened 2023-04-13 11:15 UTC by pureink

@radix-ui/react-context-menu supports "Triggers with a long-press on touch devices"

2024-04-24 15:32 UTC, ruru-m07 requested changes
just close this PR

2025-06-17 23:44 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

2025-06-24 23:45 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding! (This is an automated message)

2025-06-24 23:45 UTC, closed without merging

2025-08-04 01:45 UTC, ethan-krich commented
Why was this closed