Docs uppercase combobox values
shadcn-ui/ui pull request #1796
Opened 2023-10-21 22:33 UTC by miquelvir

cmdk uses lowecase for values for now in the callback (see: https://github.com/pacocoursey/cmdk/issues/150).

I modify the example such that no confusion is possible and it works out of the box with any string (not only lowercase ones).

Fixes https://github.com/shadcn-ui/ui/issues/889

2023-10-22 09:48 UTC, ahkhanjani requested changes

2023-10-22 09:48 UTC, ahkhanjani commented on apps/www/registry/default/example/combobox-demo.tsx
>                  onSelect={(currentValue) => {
`currentValue` is no longer needed.

2023-10-22 09:48 UTC, ahkhanjani commented on apps/www/registry/new-york/example/combobox-demo.tsx
>                  onSelect={(currentValue) => {
`currentValue` is no longer needed.

2025-03-28 23:44 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-05-18 01:43 UTC, dpnova commented
Casing is definitely an issue with select in our experience. I'll check this out and bring it up to date if possible.

2025-06-19 07:19 UTC, dpnova commented
Small update here - I tried to use cmdk v1.1.1 - but have issues with the items being disabled. I'm reading through #2944 to try figure it out.

2026-08-31 23:44 UTC, closed without merging