Fix(themes): grid falling part
shadcn-ui/ui pull request #2418
Opened 2024-01-14 08:18 UTC by chaejunlee

When resizing the [Themes](https://ui.shadcn.com/themes), the grid falls apart.

It is due to the fact that `1fr` of `grid-cols-[260px_1fr]` needs to be `minmax(0,1fr)`.

And there was a typo in the className as well, which was `grids-col-2`.

I fixed both of the mistakes.

## AS-IS

![AS-IS](https://github.com/shadcn-ui/ui/assets/48273875/a3bd828d-5d47-4b34-84c8-3e13efbe8a68)

## TO-BE

![TO-BE](https://github.com/shadcn-ui/ui/assets/48273875/177487b6-b91e-45f1-8585-07c252ad8e64)

2024-01-14 08:39 UTC, chaejunlee commented
Caught more mistakes and fixed them.

## AS-IS
![Screen Recording Jan 14](https://github.com/shadcn-ui/ui/assets/48273875/88f3e81c-882f-4a1e-ab11-63f3ab2fe25b)

## TO-BE
![Screen Recording Jan 14 (1)](https://github.com/shadcn-ui/ui/assets/48273875/94dff840-8d39-4fbd-8087-5c8c8e899e02)

2024-01-14 11:18 UTC, shadcn approved these changes
Awesome. Thank you.

2024-01-14 11:27 UTC, shadcn requested changes
@chaejunlee I'm still seeing a few issues with the grid at 768px. Would you be able to take a look please?

![GrNlUCOx](https://github.com/shadcn-ui/ui/assets/124599/1424fda8-1caa-42ac-a755-e8d2de6127e5)

2025-03-29 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-04-07 23:43 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding!

2025-04-07 23:43 UTC, closed without merging