Refactor-breadcrumb-on-www
shadcn-ui/ui pull request #2955
Opened 2024-03-08 17:25 UTC by flixlix

Use the new Breadcrumb component for own www pages

2024-03-13 04:42 UTC, shadcn requested changes
@flixlix I left a few comments. Thank you.

2024-03-13 04:42 UTC, shadcn commented on apps/www/components/copy-button.tsx
@flixlix Can we move these changes to another PR please?

2024-03-13 04:42 UTC, shadcn commented on apps/www/app/docs/[[...slug]]/page.tsx
> +} from "@/registry/default/ui/breadcrumb"
```suggestion
} from "@/registry/new-york/ui/breadcrumb"
```

2024-03-13 10:28 UTC, flixlix commented on apps/www/components/copy-button.tsx
reverted the changes, here is the other PR. Sorry for the inconvenience

https://github.com/shadcn-ui/ui/pull/2357

2025-04-08 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-04-09 07:19 UTC, flixlix commented
this is still relevant

2026-04-09 23:53 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you. (This is an automated message)

2026-04-16 23:56 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding! (This is an automated message)

2026-04-16 23:56 UTC, closed without merging