fix: prefer using nullish coalesching operator instead of a logical or in progress comp.
shadcn-ui/ui pull request #3150
Opened 2024-03-25 12:25 UTC by ritmillio

Prefer using nullish coalescing operator (`??`) instead of a logical or (`||`), as it is a safer operator.  @typescript-eslint/prefer-nullish-coalescing. -> If you have strict eslint config the current setup of progress.tsx will result in build Error.

2024-03-25 18:44 UTC, dan5py requested changes
Hi @ritmillio, please build the registry by following the [contribution guidelines](https://github.com/shadcn-ui/ui/blob/main/CONTRIBUTING.md)

2024-03-25 22:53 UTC, ritmillio commented
Hey @dan5py,

I apologize for missing the contribution guideline on app registry updates. I've gone ahead and fixed the app registry in this pull request.  Since the change only affects the registry itself, there's no need to update the documentation this time.

In the future, I'll be sure to double-check the guidelines before submitting a PR.

2024-03-27 11:00 UTC, dan5py approved these changes
👍

2024-04-23 15:19 UTC, ritmillio commented
Any update on this ?

2025-04-23 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-04-30 23:43 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding!

2025-04-30 23:43 UTC, closed without merging