fix(blocks): wrap tooltip with tooltip provider
shadcn-ui/ui pull request #3472
Opened 2024-04-13 04:26 UTC by aakash19here

FIXES #3465 

This PR wraps all the Tooltip components with ToolTipProvider

2024-04-13 04:26 UTC, aakash19here commented
Please do review whenever you get time @shadcn

2024-04-15 11:04 UTC, aakash19here commented
Can you please review this ? @shadcn

2024-04-18 08:39 UTC, aakash19here commented
Can you please review this @ruru-m07

2024-04-18 09:04 UTC, ruru-m07 requested changes
@aakash19here you can do this with another way also

you do not need to use TooltipProvider two times just wrap the full code like this.

![image](https://github.com/shadcn-ui/ui/assets/142723369/d4376701-4ad0-49e5-80ae-17f103422ae7)

still, code work perfectly

![image](https://github.com/shadcn-ui/ui/assets/142723369/6b2bcd79-1c2c-4e84-988b-e67e5ad00656)

### but the best way to face this is do something like this 

![image](https://github.com/shadcn-ui/ui/assets/142723369/a478248c-4a33-429b-80fc-469ca3151ebf)

### just use TooltipProvider in app layout

I think you need to close this PR

2024-04-18 09:16 UTC, ruru-m07 commented
@aakash19here if you see shadcn-ui properly you will notice this ===>

![image](https://github.com/shadcn-ui/ui/assets/142723369/e3c53993-c8b7-4be1-96b8-2f7a357f25e1)

they also use TooltipProvider in layout

2024-04-18 11:43 UTC, ruru-m07 commented
by the way @aakash19here we never need to add +1,364 and remove −1,284 to fix this code we just fix this under two line 

![image](https://github.com/shadcn-ui/ui/assets/142723369/a478248c-4a33-429b-80fc-469ca3151ebf)

2024-04-18 15:51 UTC, aakash19here commented
Thankyou for the explanation @ruru-m07 🤝🏻

2024-04-18 15:52 UTC, ruru-m07 commented
@aakash19here 😊👍

2024-04-25 09:50 UTC, Christophvh commented
This feels like it should be explained in the docs of the tooltip.

2024-06-21 22:11 UTC, walid1508 commented
Hi @ruru-m07,

I appreciate your solution to the issue. However, every developer who wants to use the blocks affected by this bug (dashboard-05, dashboard-06, dashboard-07, dashboard-03) will need to search for the issue on GitHub and then find your solution. This is why I believe @aakash19here's approach is better, as it will fix the bug for everyone.

Thank you!

2024-07-27 14:38 UTC, walid1508 approved these changes

2024-07-27 14:38 UTC, walid1508 approved these changes

2025-09-19 06:01 UTC, shadcn commented
This is now available in the latest tooltip.tsx. Thanks for the PR @aakash19here

2025-09-19 06:01 UTC, closed without merging