fix(combobox-demo): add CommandList to work
shadcn-ui/ui pull request #3541
Opened 2024-04-19 17:19 UTC by arturmois

add CommandList to work

2024-04-20 05:32 UTC, ruru-m07 requested changes

2024-04-20 05:32 UTC, ruru-m07 commented on apps/www/__registry__/default/example/combobox-demo.tsx
> +import * as React from "react"
is this change required?

2025-04-29 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-05-06 23:43 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding!

2025-05-06 23:43 UTC, closed without merging