fix(www): ensure that there is a value when changing the panel size
shadcn-ui/ui pull request #3641
Opened 2024-05-01 15:46 UTC by ItsValerius

This PR fixes the issue described here:
#3640

2024-05-03 14:20 UTC, flixlix requested changes
I would suggest the following changes:

```ts
const [currentSize, setCurrentSize] = React.useState("100")
```

```ts
value={currentSize}
onValueChange={(value) => {
  if (resizablePanelRef.current && value) {
    setCurrentSize(value)
    resizablePanelRef.current.resize(parseInt(value))
  }
}}
```

this way, when clicking a size that was already selected, we can make sure that it doesn't get deselected. By making the toggle group controlled we make sure at least one is always selected

2024-05-06 13:23 UTC, ItsValerius commented
> I would suggest the following changes:
> 
> ```ts
> const [currentSize, setCurrentSize] = React.useState("100")
> ```
> 
> ```ts
> value={currentSize}
> onValueChange={(value) => {
>   if (resizablePanelRef.current && value) {
>     setCurrentSize(value)
>     resizablePanelRef.current.resize(parseInt(value))
>   }
> }}
> ```
> 
> this way, when clicking a size that was already selected, we can make sure that it doesn't get deselected. By making the toggle group controlled we make sure at least one is always selected

Good idea! 
I made some changes to your suggestions to make sure the buttons would still work, if the ResizablePanel was changed by dragging it around.

2024-05-06 13:35 UTC, flixlix approved these changes

2025-05-06 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-05-14 23:43 UTC, shadcn commented
This PR has been automatically closed due to one year of inactivity. Thank you for your understanding!

2025-05-14 23:43 UTC, closed without merging