feat:toggle group
shadcn-ui/ui pull request #53
Opened 2023-02-03 21:17 UTC by KXLAA

This PR add the Toggle group component, you can see the demo of how it looks on both light & dark modes below:

![2023-02-03 10 01 13 pm](https://user-images.githubusercontent.com/87288429/216712214-983389f8-66dd-4cea-a74d-800cb3a33181.gif)

2023-02-04 06:49 UTC, shadcn commented
@KXLAA This is a great start. Can you update the style to match the new `<Toggle />` component we just added? We are looking for `default` and `outline` variants.

2023-02-04 10:48 UTC, shadcn requested changes
Minor nit. Build is failing. Thank you.

2023-02-04 10:48 UTC, shadcn commented on apps/www/content/docs/primitives/toggle-group.mdx
> +<ComponentExample src="/components/examples/toggle-group/SM.tsx">
```diff
- <ComponentExample src="/components/examples/toggle-group/SM.tsx">
+ <ComponentExample src="/components/examples/toggle-group/sm.tsx">
```

2023-02-04 17:43 UTC, shadcn commented
@KXLAA This is looking good. If it's OK with you, I'll push a few minor style fixes and then we can merge.

2023-02-04 17:57 UTC, KXLAA commented
> @KXLAA This is looking good. If it's OK with you, I'll push a few minor style fixes and then we can merge.

Sure thing. Thanks

2023-06-11 20:23 UTC, filipjnc commented
Is this not ready to go?

2023-07-03 01:11 UTC, ImBIOS approved these changes
LGTM, Like it 👍

2023-07-03 01:40 UTC, ImBIOS requested changes

2023-07-03 01:40 UTC, ImBIOS commented on apps/www/components/ui/toggle-group.tsx
> +          "bg-slate-900 text-white  hover:bg-slate-700 dark:bg-slate-50 dark:text-slate-900 data-[state=on]:text-slate-900 ",
some white space warning here and because of I like to see tailwind sorted className, I think this className isn't sorted with any rules at all.

2023-09-18 12:18 UTC, shadcn commented
I'll take a look at this again. Assigning...

2023-11-12 11:58 UTC, shadcn commented
@KXLAA Would you be ok if we go with this (updated) PR https://github.com/shadcn-ui/ui/pull/1547 for the toggle group? I appreciate that you were the first one with the toggle group implementation. Thank you.

2023-11-12 12:45 UTC, KXLAA commented
> @KXLAA Would you be ok if we go with this (updated) PR #1547 for the toggle group? I appreciate that you were the first one with the toggle group implementation. Thank you.

yeah sure, thank you

2023-11-12 18:04 UTC, shadcn commented
Thanks @KXLAA. Appreciate it!

2023-11-12 18:04 UTC, closed without merging