Update badge.tsx tag name to `span`
shadcn-ui/ui pull request #674
Opened 2023-06-23 14:19 UTC by pablolizardo

Badge should behave as inline elements , so `div` tag isn't propper.  
Also some frameworks (like nextjs) will return a warning of `validateDOMNesting(...): <div> cannot appear as a descendant of <p>`

2023-06-23 14:53 UTC, dan5py requested changes
You also need to update the `badge.json` files in the `public/registry` folder. That is where the CLI gets the components from.

2023-06-23 15:06 UTC, dan5py requested changes
Also the `BadgeProps` in the `badge.tsx` files must extend `React.HTMLAttributes<HTMLSpanElement>` instead of the `DivElement`

2025-03-27 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-10-05 10:30 UTC, closed without merging

2025-10-05 10:30 UTC, shadcn commented
Hi. We're closing some old PRs as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn