fix(app): Remove required id from toast (fixed #721)
shadcn-ui/ui pull request #722
Opened 2023-06-26 12:27 UTC by AnandChowdhary

This PR fixes #721 by removing the unnecessary `id` requirement from the `props` when updating a toast.

2023-06-26 12:38 UTC, dan5py requested changes
Two main things you need to do:
- update the `new-york` theme's `useToast` file
- update the registry

You can directly use this Typescript type instead of hard coding it.
https://github.com/shadcn/ui/blob/ab836d1ab3b36471b99de645d5ec997a598921bf/apps/www/registry/default/ui/use-toast.ts#L141

2023-06-26 15:03 UTC, AnandChowdhary commented
All done, thanks @dan5py!

2023-06-27 13:49 UTC, dan5py commented
> How would I go about updating the registry?

You need to run `pnpm build:registry`

2023-11-05 12:43 UTC, oncet approved these changes

2023-11-05 12:55 UTC, oncet commented
> > How would I go about updating the registry?
> 
> You need to run `pnpm build:registry`

@AnandChowdhary have you tried this? I wanted to push it but I don't have access rights.

2025-03-27 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-03-28 13:52 UTC, AnandChowdhary commented
@shadcn Flagging for you!

2025-10-05 10:30 UTC, shadcn commented
Hi. We're closing some old PRs as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn

2025-10-05 10:30 UTC, closed without merging