docs(www): remove unused Separator import from CardDemo example component
shadcn-ui/ui pull request #740
Opened 2023-06-27 10:26 UTC by Kobu

2023-06-27 11:15 UTC, dan5py requested changes
Great. Please remove it also from the `new-york` theme one.

2023-06-27 17:55 UTC, Kobu commented
> Great. Please remove it also from the `new-york` theme one. @dan5py 
Deleted and force amended to the previous commit to keep things clean

2023-06-27 18:47 UTC, dan5py approved these changes
👍

2025-03-27 23:43 UTC, shadcn commented
This PR has been automatically marked as stale due to one year of inactivity. It will be closed in 7 days unless there’s further input. If you believe this PR is still relevant, please leave a comment or provide updated details. Thank you.

2025-10-05 10:30 UTC, shadcn commented
Hi. We're closing some old PRs as outdated. If this is still relevant, leave a message, we'll reopen it. Thank you. Appreciate your contribution to the project - shadcn

2025-10-05 10:30 UTC, closed without merging