Add Dark Mode Guide for Vite with React
shadcn-ui/ui pull request #750
Opened 2023-06-27 20:16 UTC by CarlosZiegler

This PR adds a guide for implementing dark mode in a Vite project with React. The guide includes the following steps:

1. Creating a theme provider using React's Context API.
2. Wrapping the root layout with the ThemeProvider.
3. Adding a mode toggle to switch between light and dark mode.

The guide is intended to be clear and easy to follow, allowing developers to implement dark mode in their Vite and React projects effectively.

Please review and let me know if any changes are required.

PS: Added a GIF but I am not so familiar to put it into MDX :(

2023-06-27 21:13 UTC, dan5py requested changes
Please keep the same layout with the Tabs as the vite-docs (check this PR #714). Also remove the `ThemeVite.gif` and the `package-lock.json`.

2023-06-28 05:12 UTC, CarlosZiegler commented
@dan5py updated.

2023-06-28 08:53 UTC, dan5py requested changes
Could you please remove the titles from the tabs content?

2023-06-28 20:13 UTC, CarlosZiegler commented
@dan5py updated

2023-06-29 21:13 UTC, NikharPandya commented
@dan5py and @CarlosZiegler , rather than this being on the installation page what if we make the dark mode page similar to instalation page and show tabs for next.js remix and vite dark mode configuration ?

2023-06-29 21:15 UTC, dan5py commented
@NikharPandya I was thinking the same thing.

2023-06-29 21:23 UTC, NikharPandya commented
@dan5py I could help to implement that.

2023-07-06 03:16 UTC, NikharPandya commented
@dan5py  #814 Resolves this pr with a new grid layout (similar to the installation page), we could close this.

2023-07-09 17:36 UTC, ap-1 commented
> @dan5py and @CarlosZiegler , rather than this being on the installation page what if we make the dark mode page similar to instalation page and show tabs for next.js remix and vite dark mode configuration ?

Is there a PR open for this? I recommend using the existing [`next-themes`](https://www.npmjs.com/package/next-themes) package for the next.js configuration

2024-02-15 20:00 UTC, raghavjindalll commented
Can we implement the dark mode using react and javascript?

2024-02-16 14:35 UTC, CarlosZiegler commented
> Can we implement the dark mode using react and javascript?

Here the docs :
https://ui.shadcn.com/docs/dark-mode/vite

2024-11-07 20:38 UTC, closed without merging