feat(cli): add support for custom Tailwind prefix transformer
shadcn-ui/ui pull request #770
Opened 2023-06-29 13:41 UTC by Bekacru

https://github.com/shadcn/ui/issues/535
Hey there, It seems that no one has addressed this issue yet. This pull request introduces a new feature to the CLI, allowing users to define a custom Tailwind prefix transformer. With this enhancement, users can specify a custom prefix value when executing the `init` command. This custom prefix will be utilized to generate class names for components and utilities.

The implementation covers updates to both the configuration schema and the init command. The configuration schema now includes a new optional field called prefix. As a result, users who have customized their configuration won't be required to update it, and the CLI will not throw any errors with existing configurations.

Please take a moment to review the changes and provide your feedback.

2023-06-30 07:59 UTC, Bekacru commented
hey @dan5py I know u guys are probably very busy but just wanna know if u guys have any taught or feedbacks on this

2023-06-30 08:26 UTC, dan5py requested changes
Hi @Bekacru, thank you for this great PR.

I see only one problem:
https://github.com/shadcn/ui/blob/eee7ce68798b9345cb969942cd279c3acc054ad6/apps/www/scripts/build-registry.ts#L255-L262

The classes applied in the css file are missing the prefix when it gets added, so they cannot be found.

Apart from that I think that it's really well done.

2023-06-30 10:40 UTC, Bekacru commented
hi @dan5py thanks! Oh yeah, I just added that in with the latest commit, so it should be fixed now.

2023-06-30 10:45 UTC, dan5py approved these changes
👍 @shadcn

2023-07-13 07:39 UTC, bim-oulabi commented
I would really like this feature as the manual work on this is kinda difficult since am working on a monorepo based UI,

Thanks

2023-07-13 11:19 UTC, firebotQL commented
I do need it as well, as my chrome extension I am building based on shadcn intervening on some of the websites which also built using tailwind. So I cannot release it without major manual rework. In practise I need styling not to clash...

Could you guys have a look into mergins this PR as soon as please? Thanks!

2023-07-13 20:40 UTC, Bekacru commented
hey @shadcn you should review this when you get time, I'm happy to help if there is something that's holding this back.

2023-07-28 00:53 UTC, yovanoc commented
Oh we really need this too ! How could we help ?

2023-08-15 09:27 UTC, Pipe-Runner commented
This is a needed feature for working in a mono repo setup. I am stuck for now without this.

2023-08-16 09:52 UTC, m10rten reviewed
As a non-code-owner, I think it looks good, few things I would have done different.

2023-08-16 09:52 UTC, m10rten commented on packages/cli/src/utils/transformers/transform-tw-prefix.ts
> +    for (let line of lines) {
const line?

2023-08-16 09:52 UTC, m10rten commented on packages/cli/src/commands/init.ts
> +
empty lines

2023-08-16 09:52 UTC, m10rten commented on packages/cli/src/utils/transformers/transform-tw-prefix.ts
> +            TODO://this is very hacky way find tailwind classes but for current components it works. Need to find a better way
meanwhile is there a better way?

2023-09-10 23:19 UTC, GiancarlosIO commented
🙏🏼

2023-09-20 04:02 UTC, shadcn commented
Looking into this.

2023-09-26 23:37 UTC, tecoad commented
> Looking into this.

Any news on this? Very needed feature actually.
Just actually noticed a little bug: when using tailwind prefix, the classes passed as props to the ui components don't actually override the component defaults.  Only if we use the !prefix- modifier.

2023-09-27 00:10 UTC, tecoad commented
> Looking into this.

Any news on this? Such a great feature to have.
I just noticed the cn function at utils.ts also would have to be updated so twMerge can receive also the prefix to work as intended:

const twMerge = extendTailwindMerge({
  prefix: 'wdg-',
})

Otherwise, can experience some conflicts for overiding default classes.

2023-10-10 23:17 UTC, HowieG commented
Bump could definitely use this! Building an embedded chatbot and the host site's styles are leaking so this would prevent classname conflict. Should probably just implement a Shadow DOM instead.

2023-11-16 20:36 UTC, wadefletch commented
Any update on this? This is an important prerequisite to being able to safely use shadcn components in a monorepo and/or use them in distributed components that will be embedded in sites with their own (potentially different and conflicting) tailwind configurations.

2023-11-21 18:35 UTC, v1adko commented on packages/cli/src/commands/init.ts
> +    {
I think this question should be moved down after tailwindConfig and if config exists, the default answer could be pre-populated based on config.

2023-11-21 18:38 UTC, v1adko commented on packages/cli/src/utils/templates.ts
> +}`
not sure if the empty end line was removed or it was like this before, but I'd suggest to keep it.
Also I see "prefix" option to be defined closer to the top of the config and not the end (maybe I'm mistaking and haven't seen enough configs in the wild). I think it's more visual on the top.

2023-11-21 18:40 UTC, v1adko commented on packages/cli/src/utils/transformers/transform-tw-prefix.ts
> +            TODO://this is very hacky way find tailwind classes but for current components it works. Need to find a better way
Also comment looks messed up.

2023-12-11 09:31 UTC, Medaillek commented
Hey, I've written this function you can use in javascript to convert className to prefixed className :
```ts
    function addTwPrefix(string = '', prefix='tw-') {
        let finalString = ''
        const all =  string.split(/\s/g)
        for (const str of all) {
            const isDoubleDot = str.indexOf(':')
            if (isDoubleDot > -1) {
                const strToUpdate = str.split(':')
                const updatedClass = `${prefix}${strToUpdate[1]}`
                finalString += ` ${strToUpdate[0]}:${updatedClass}`
            } else {
                finalString += ` tw-${str}`
            }
        }
        return finalString
    }
```

Not sure if its optimal but it does the job.

2023-12-14 06:06 UTC, othorizon commented
> Hey, I've written this function you can use in javascript to convert className to prefixed className until the cli will be updated :嘿，我已经编写了这个函数，您可以在 javascript 中使用它来将 className 转换为带前缀的 className，直到 cli 更新为止：
> 
> ```ts
>             function addTwPrefix(string = '', prefix = 'tw-') {
>       let finalString = ''
>       const all = string.split(/\s/g)
>       for (let str of all) {
>         const isDoubleDot = str.indexOf(':')
>         if (isDoubleDot > -1) {
>           let strToUpdate = str.split(':')
>           if (strToUpdate[1].startsWith('-')) {
>             prefix = `-${prefix}`
>             strToUpdate[1] = strToUpdate[1].slice(1)
>           }
>           const updatedClass = `${prefix}${strToUpdate[1]}`
>           finalString += ` ${strToUpdate[0]}:${updatedClass}`
>         } else {
>           if (str.startsWith('-')) {
>             prefix = `-${prefix}`
>             str = str.slice(1)
>           }
>           finalString += ` ${prefix}${str}`
>         }
>       }
>       return finalString
>     }
> ```
> 
> Not sure if its optimal but it does the job.

thank you very much ,bro.

2023-12-14 06:20 UTC, othorizon commented
@Medaillek thanks agin.I made some modifications, ignoring those that already include the prefix,so you can inject it in the "cn" function and use it freely.


```
import { type ClassValue, clsx } from "clsx"
import { twMerge } from "tailwind-merge"
 
export function cn(...inputs: ClassValue[]) {
  return addTwPrefix(twMerge(clsx(inputs)))
}

function addTwPrefix(string = '', prefix = 'tw-') {
  let finalString = ''
  const all = string.split(/\s/g)
  for (let str of all) {
    if (!str.trim()) {
      continue; // ignore empty
    }
    const isDoubleDot = str.indexOf(':')
    if (isDoubleDot > -1) {
      let strToUpdate = str.split(':')
      if (strToUpdate[1].startsWith('-')) {
        prefix = `-${prefix}`
        strToUpdate[1] = strToUpdate[1].slice(1)
      }
      const updatedClass = strToUpdate[1].startsWith(prefix) ? strToUpdate[1] : `${prefix}${strToUpdate[1]}`;
      finalString += ` ${strToUpdate[0]}:${updatedClass}`
    } else {
      if (str.startsWith('-')) {
        prefix = `-${prefix}`
        str = str.slice(1)
      }
      finalString += str.startsWith(prefix) ? ` ${str}` : ` ${prefix}${str}`;
    }
  }
  return finalString
}
```

2023-12-14 10:15 UTC, Medaillek commented
> > Hey, I've written this function you can use in javascript to convert className to prefixed className until the cli will be updated :
> > ```ts
> >             function addTwPrefix(string = '', prefix = 'tw-') {
> >       let finalString = ''
> >       const all = string.split(/\s/g)
> >       for (let str of all) {
> >         const isDoubleDot = str.indexOf(':')
> >         if (isDoubleDot > -1) {
> >           let strToUpdate = str.split(':')
> >           if (strToUpdate[1].startsWith('-')) {
> >             prefix = `-${prefix}`
> >             strToUpdate[1] = strToUpdate[1].slice(1)
> >           }
> >           const updatedClass = `${prefix}${strToUpdate[1]}`
> >           finalString += ` ${strToUpdate[0]}:${updatedClass}`
> >         } else {
> >           if (str.startsWith('-')) {
> >             prefix = `-${prefix}`
> >             str = str.slice(1)
> >           }
> >           finalString += ` ${prefix}${str}`
> >         }
> >       }
> >       return finalString
> >     }
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Not sure if its optimal but it does the job.
> 
> thank you very much ,bro. but tailwindcss do not support construct class names dynamically

Yes I know, here the thing is to use node js to create your classes, instead of manually adding your prefix on each class. Copy paste the classes you want to convert, it's painfull but less than pointing your cursor in front of each class when the component is generated

2023-12-21 19:07 UTC, Medaillek commented
I'm comming back again with a greater solution for anyone struggling : https://github.com/Medaillek/shadcn-ui-tailwind-prefix/tree/main

 - Copy paste the code in the `.cjs` file 
- Update `const prefix = "tw-"`
- Update the path to your shadcn-ui components directory
- run it using nodeJS

2023-12-21 21:41 UTC, shadcn approved these changes
I made some changes to how the transformer handles classes (including support for classes inside `cva` and `cn`). We're green!

Thanks for your work on this @Bekacru Appreciate it.

2023-12-21 21:42 UTC, merged

2023-12-21 22:32 UTC, Kinfe123 commented
Great job @Bekacru

2026-07-29 04:38 UTC, Maks-T commented
Hi everyone! 👋

If you're dealing with Tailwind CSS class collisions or style leaks when sharing UI components / embedding apps in a monorepo, I built an AST-driven CLI tool that automates Tailwind prefixing and complete style isolation: **[`tailwind-prefix-migrator`](https://github.com/Maks-T/tailwind-prefix-migrator)**.

### Key Features:
- 🎯 **AST-Driven Precision (Babel & PostCSS):** Safely prefixes Tailwind classes across JS, TSX, SCSS, `@apply` rules, and `cva()` definitions without regular expression edge-case bugs.
- 🛡 **CSS Layer & Variable Isolation:** Automatically wraps `@tailwind` directives in custom `@layer` rules and prefixes CSS variables (e.g., `--primary` ➔ `--calc-primary`) to prevent style leaks into host applications.
- 📦 **Config Sync:** Updates `prefix` and `preflight` settings in `tailwind.config.js` and `components.json` (shadcn/ui).
- 🔄 **Instant Rollback:** Reverse prefix migrations anytime using `tpm revert`.

You can test it in dry-run mode via `npx`:

```bash
npx tailwind-prefix-migrator init
npx tailwind-prefix-migrator apply --dry-run