feat(cli): A bit smarter cli
shadcn-ui/ui pull request #823
Opened 2023-07-03 22:20 UTC by Bekacru

Hey @shadcn and @dan5py I was seeing issues like these https://github.com/shadcn/ui/issues/818 appear repeatedly. The issue, I believe, stems from using constant initial values on the cli, so I figured it would make sense to offer better initial values based on project info. I'm not sure whether you guys are working on it with more features, but since it's not a difficult task, I thought I'd give it a shot.

2023-07-03 22:44 UTC, dan5py commented
Hi @Bekacru. You're right, those kind of issues are more and more frequent. I need to test your solution but it looks promising. Thank you 💪.

2023-07-03 23:15 UTC, dan5py commented
Just tested it out and it works very well. Just to complete your work could you please run this command:

```bash
pnpm format:write
```

Because when running the `check` it complains for the formatting. Thanks again, good job!

2023-07-03 23:15 UTC, dan5py commented
@shadcn

2023-07-03 23:20 UTC, dan5py commented
@shadcn

2023-07-03 23:24 UTC, Bekacru commented
done

2023-07-03 23:42 UTC, dan5py approved these changes
@shadcn 👍

2023-07-04 19:25 UTC, shadcn commented
@Bekacru Awesome work! Now that we have docs for several frameworks, I wonder if we can auto-detect framework and provide better defaults for the CLI?

2023-07-04 19:51 UTC, Bekacru commented
@shadcn thanks! yeah that's possible. I think most of them use similar naming like app, pages, and components, as well as the folder alias is the same so we only need to tweak them slightly for each of them.  Do u want me to work on that?

2023-07-04 20:01 UTC, shadcn commented
> Do u want me to work on that?

If you got time, yes please!

2023-07-04 20:07 UTC, dan5py commented
I should also have time these days. I’ll see what I can do. 💪

2023-07-04 20:38 UTC, Bekacru commented
> > Do u want me to work on that?
> 
> If you got time, yes please!

on it 👍

2023-07-05 06:59 UTC, Bekacru commented
@shadcn and @dan5py started working on this. since all of them follow almost have similar folder structure, the present projectInfo is sufficient for the most part, but I added a styles folder resolver to better identify the global CSS. Let me know if there is anything I missed.

2023-07-05 14:05 UTC, dan5py requested changes
Thank you. I suggest just few changes.

2023-07-05 14:05 UTC, dan5py commented on packages/cli/src/commands/init.ts
> +import { getInitialValues } from "../utils/get-initial-values"
To respect the syntax used in the other files, use the aliased import:
```ts
import { getInitialValues } from "@/src/utils/get-initial-values"
```

2023-07-05 14:05 UTC, dan5py commented on packages/cli/src/utils/get-initial-values.ts
> +import { getProjectInfo, resolveProjectDir } from "./get-project-info"
To respect the syntax used in the other files, use the aliased import:
```ts
import { getProjectInfo, resolveProjectDir } from "@/src/utils/get-project-info"
```

2023-07-05 14:34 UTC, Bekacru commented on packages/cli/src/utils/get-project-info.ts
> +export function getStylesDir() {
`const stylesDir = possiblePaths.find(path => existsSync(path.resolve(path))) || null;`
path will conflict with the imported path so changed it to possible path

2023-07-12 16:31 UTC, shadcn commented
@Bekacru quick update here. This is looking good. I'll review and get this merged this week.

2023-07-14 11:39 UTC, shadcn commented
I started testing this and it looks like we need to put in some work. We need to update the helpers so that config is read from `cwd` eg. `getTsConfig` is reading the local `tsconfig.json` and not from target dir.

2023-07-14 17:46 UTC, Bekacru commented
> I started testing this and it looks like we need to put in some work. We need to update the helpers so that config is read from `cwd` eg. `getTsConfig` is reading the local `tsconfig.json` and not from target dir.

I'm not sure if this is what you're looking for, but adde cwd to all helper path resolvers in the same way as you did for getConfig.

2024-01-28 09:01 UTC, shadcn commented
@Bekacru We shipped automatic detection in the cli. We're doing this on a framework-basis. I'm going to close this issue as done. Feel free to reopen if you have any questions. Thanks for your work on this PR. Appreciate it.

2024-01-28 09:01 UTC, closed without merging